CREATE TABLE IF NOT EXISTS `NCCS_Address_Metadata_org_loc` (
  `EIN2` VARCHAR(9) NOT NULL,
  `ORG_FISCAL_YEAR` INT NOT NULL,
  `ORG_ADDR_FULL` VARCHAR(72) NOT NULL,
  `ORG_ADDR_MATCH` VARCHAR(102) NOT NULL,
  `LONGITUDE` DOUBLE NOT NULL,
  `LATITUDE` DOUBLE NOT NULL,
  `ADDR_TYPE` VARCHAR(16) NOT NULL,
  `GEOCODER_SCORE` DOUBLE NOT NULL,
  `GEOCODER_MATCH` VARCHAR(1) NOT NULL,
  `CENSUS_BLOCK_FIPS` VARCHAR(15),
  PRIMARY KEY (`EIN2`)
);
