CREATE TABLE IF NOT EXISTS `NCCS_Address_Metadata_cbsa` (
  `CENSUS_CBSA_FIPS` VARCHAR(5),
  `CENSUS_CBSA_NAME` VARCHAR(46),
  `CENSUS_CBSA_LEGAL_NAME` VARCHAR(57),
  `CENSUS_CBSA_LEGAL_CODE` VARCHAR(2),
  `CENSUS_CSA_FIPS` VARCHAR(3),
  UNIQUE (`CENSUS_CBSA_FIPS`)
);
