CREATE TABLE IF NOT EXISTS `NCCS_Address_Metadata_counties` (
  `CENSUS_COUNTY_FIPS` VARCHAR(3) NOT NULL,
  `CENSUS_COUNTY_NAME` VARCHAR(46) NOT NULL,
  `CENSUS_STATE_FIPS` VARCHAR(2) NOT NULL,
  `CENSUS_CBSA_FIPS` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`CENSUS_COUNTY_FIPS`, `CENSUS_STATE_FIPS`)
);
