CREATE TABLE IF NOT EXISTS `NCCS_Address_Metadata_census_blocks` (
  `CENSUS_BLOCK_FIPS` VARCHAR(15) NOT NULL,
  `CENSUS_BLOCK_CODE` VARCHAR(4) NOT NULL,
  `CENSUS_BLOCK_NAME` VARCHAR(10) NOT NULL,
  `CENSUS_BLOCK_HOUSING_UNIT_COUNT` VARCHAR(4),
  `CENSUS_BLOCK_POPULATION_COUNT` VARCHAR(4),
  `CENSUS_FUNCTIONAL_STATUS` VARCHAR(1) NOT NULL,
  `CENSUS_URBAN_AREA_CODE` VARCHAR(5),
  `CENSUS_TRACT_FIPS` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`CENSUS_BLOCK_FIPS`)
);
